# Generated by Django 3.1.1 on 2020-10-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201007_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='darkmode',
            field=models.BooleanField(default=False, verbose_name='Dark mode'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=1500, verbose_name='Tactics rating'),
        ),
    ]
