# Generated by Django 3.1.1 on 2020-10-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201015_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_tactics_correct',
            field=models.IntegerField(default=10, verbose_name='Total Tactics Correct'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_tactics_incorrect',
            field=models.IntegerField(default=10, verbose_name='Total Tactics Incorrect'),
        ),
    ]
