# Generated by Django 3.1.1 on 2021-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201022_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='FEN string')),
                ('evaluation_before', models.IntegerField(verbose_name='Evaluation before')),
                ('evaluation_after', models.IntegerField(verbose_name='Evaluation after')),
                ('best_move', models.CharField(max_length=200, verbose_name='Best Move')),
                ('variation', models.TextField(verbose_name='Variation (JSON-serialized)')),
                ('classifications', models.TextField(verbose_name='Classifications (JSON-serialized)')),
                ('rating', models.FloatField(default=1500, verbose_name='Difficulty rating')),
                ('side_to_move', models.IntegerField(verbose_name='Side to move')),
            ],
        ),
    ]
