# Generated by Django 3.2 on 2021-04-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tactic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactic',
            name='source_set',
            field=models.CharField(default='No update', max_length=1000, verbose_name='Source file'),
        ),
    ]
